# Generated by Django 5.1.1 on 2024-10-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tgl_pinjam', models.DateField(blank=True)),
                ('tgl_kembali', models.DateField(blank=True)),
                ('judul_buku', models.TextField()),
            ],
        ),
    ]
