# Generated by Django 5.1.1 on 2024-10-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=12)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=100)),
                ('kategori', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='daftar_hadir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tgl_kunjungan', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='denda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=12)),
                ('nama', models.CharField(max_length=100)),
                ('denda', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jenis_denda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=20)),
                ('terlambat', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tgl_pinjam', models.DateField(blank=True)),
                ('tgl_kembali', models.DateField(blank=True)),
                ('judul_buku', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=12)),
                ('nama_petugas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_denda', models.DateField(blank=True)),
                ('besar_transaksi', models.CharField(max_length=5, null=True)),
                ('nama_petugas', models.CharField(max_length=100)),
            ],
        ),
    ]
