# Generated by Django 5.1.1 on 2024-10-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anggota',
            old_name='nama',
            new_name='nama_anggota',
        ),
        migrations.RenameField(
            model_name='anggota',
            old_name='nim',
            new_name='nim_anggota',
        ),
        migrations.RenameField(
            model_name='buku',
            old_name='kategori',
            new_name='kategori_buku',
        ),
        migrations.RenameField(
            model_name='daftar_hadir',
            old_name='nama',
            new_name='nama_anggota',
        ),
        migrations.RenameField(
            model_name='denda',
            old_name='nama',
            new_name='nama_anggota',
        ),
        migrations.RenameField(
            model_name='denda',
            old_name='nim',
            new_name='nim_anggota',
        ),
        migrations.RenameField(
            model_name='peminjaman',
            old_name='nama',
            new_name='nama_anggota',
        ),
        migrations.RenameField(
            model_name='petugas',
            old_name='nim',
            new_name='nim_petugas',
        ),
    ]
