# Generated by Django 5.1.1 on 2024-10-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_denda', models.DateField(blank=True)),
                ('besar_transaksi', models.CharField(max_length=5, null=True)),
                ('nama_petugas', models.CharField(max_length=100)),
            ],
        ),
    ]
