# Generated by Django 5.1.1 on 2024-10-09 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jenis_denda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jenis_denda',
        ),
    ]
